export const GET_TIMESERIES = "GET_TIMESERIES";
export const GET_GLOBAL = "GET_GLOBALDATA";
export const TIMESERIES_LOADING = "TIMESERIES_LOADING";
export const GLOBAL_LOADING = "GLOBAL_LOADING";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
