export const GET_TIME_SERIES = "GET_TIME_SERIES";
export const GET_GLOBAL = "GET_GLOBAL";
export const TIME_SERIES_LOADING = "TIME_SERIES_LOADING";
export const GLOBAL_LOADING = "GLOBAL_LOADING";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_SELECTED_COUNTRY = "SET_SELECTED_COUNTRY";
export const SELECTED_COUNTRY_LOADING = "SELECTED_COUNTRY_LOADING";
